### PR TITLE
Added saving sequence and SequencerDialog to refactor branch

### PR DESCRIPTION
**Pull request by mcdo0486**
Fixed not being able to add root item if file not loaded. Moved TreeWidget functionality to SequencerTreeView. Added SequencerDialog. Renamed SequenceFileHandle to Sequencer as file isn't required.

### CODE REVIEW

**Comment by mcdo0486** [comment]
I missed you added some things yesterday, I think things are sorted now.

**Comment by msmttchr** [comment]
> I missed you added some things yesterday, I think things are sorted now. It looks like we both removed debug code, but I also change the class previously named SequenceFileHandle save method. I used the github web interface to fix conflicts, but introduced a typo which is fixed in [11e2296](https://github.com/wnluke/pymeasure/pull/22/commits/11e229664d5f72263edaabfd549dc69582443d4b)

@mcdo0486, thanks for your PR, I have tried to apply your enhancements and fixes minimizing the code changes.
In particular, I have done the following:
- sequencer.py: just the fixes and not name changes
- sequencer_widget.py: Added class SequenceDialog, removed preview from save sequence, added your preview to load sequence.

Could You please have a look whether they are OK with You ?

**Comment by mcdo0486** [comment]
@msmttchr I guess I'll use this thread to capture other changes.

I was also thinking that it isn't obvious from the new interface that the sequence is editable:

new: image

old: image

It isn't obvious that you need to double click on items to edit them. Also, if you double click on the level number nothing happens, and nothing should, but that can be confusing to the user who would assume they can't double click on other items. The previous interface makes it more clear that you can edit the parameter and sequence items.

I haven't looking too much into it, but there are options at least for double click behavior with QTreeView that I was going to check out.

**Comment by msmttchr** [comment]
> One problem with the current branch is that if you run ManagedWindow and do not pass the `sequence_file` argument, then you can not add a root item or any item. This was fixed in [6a2aa33](https://github.com/wnluke/pymeasure/pull/22/commits/6a2aa33ce79b84b16a316e2df7d852f20ebe913f)
> 

Thanks for raising this point, I didn't notice. I will test this case and get back to you.
> There is also behavior that is different from the original implementation, which I think probably should be carried over. In the previous implementation if you opened up a new sequence file it would append the sequence to the current list of sequences, instead of replacing it.

Good point. I will check this.
Thanks for your help.

**Comment by mcdo0486** [comment]
> > There is also behavior that is different from the original implementation, which I think probably should be carried over. In the previous implementation if you opened up a new sequence file it would append the sequence to the current list of sequences, instead of replacing it.
> 
> Good point. I will check this. Thanks for your help.

That is partly why I moved `SequencerFileHandle` to receiving file names instead of one to one relation with a file stream, but I hadn't added appending sequences in this PR. I first wanted to clarify if you think that feature should be carried over.

**Comment by msmttchr** [comment]
> @msmttchr I guess I'll use this thread to capture other changes.
> 
> I was also thinking that it isn't obvious from the new interface that the sequence is editable:
> 
> new: image
> 
> old: image
> 
> It isn't obvious that you need to double click on items to edit them. Also, if you double click on the level number nothing happens, and nothing should, but that can be confusing to the user who would assume they can't double click on other items. The previous interface makes it more clear that you can edit the parameter and sequence items.
> 
> I haven't looking too much into it, but there are options at least for double click behavior with QTreeView that I was going to check out.

I think there is some setting like "persistent editor" to avoid the double click. I need to double check this.

**Comment by mcdo0486** [comment]
In this PR I added the appending behavior when loading a sequence  with a file obj[28562b2](https://github.com/wnluke/pymeasure/pull/22/commits/28562b29abde942e5d5785624594d40153edf04f)

**Comment by mcdo0486** [comment]
In this PR I added the appending behavior when loading a sequence with a filename [759ed18](https://github.com/wnluke/pymeasure/pull/22/commits/759ed1803d46392f7b6a61d75eba5ba834e5ea92)

I'll also add it as a standalone PR

**Pull request closed without merging**
